openapi: 3.0.0
servers: []
info:
  version: "1.0.0"
  title: Template-Fastify-Api
  description: >-
    This is an APi Documentation of Template-Fastify-Api.
paths:
  /users:
    get:
      summary: List all Users
      description: >-
        This operation return a list of users
      responses:
        "200":
          description: OK
      tags:
        - user
    post:
      summary: Create an User
      description: >-
        This operation return a list of users
      responses:
        "200":
          description: OK
      tags:
        - user
  /users/{id}:
    get:
      summary: Get a user by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: UUID char of the user to get
      responses:
        "200":
          description: OK
      tags:
        - user
security:
  - implicit:
      - read
      - write
components:
  schemas: {}
  securitySchemes:
    implicit:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "http://example.com/oauth/auth"
          scopes:
            write: allows modifying resources
            read: allows reading resources
